### ISSUE TITLE
 No module named 'loud'

### ISSUE THREAD

**Issue by GuyKh** [t0mer/locationsharing#7]
Docker container fails for

```
Traceback (most recent call last):
  File "/app/app.py", line 20, in <module>
    service = Service(cookies_file=cookies_file, authenticating_account=google_email)
  File "/usr/local/lib/python3.6/dist-packages/locationsharinglib/locationsharinglib.py", line 101, in __init__
    self._session = self._validate_cookie(cookies_file or '')
  File "/usr/local/lib/python3.6/dist-packages/locationsharinglib/locationsharinglib.py", line 104, in _validate_cookie
    session = self._get_authenticated_session(cookies_file)
  File "/usr/local/lib/python3.6/dist-packages/locationsharinglib/locationsharinglib.py", line 123, in _get_authenticated_session
    session.cookies.update(pickle.load(cfile))
ModuleNotFoundError: No module named 'loud'
```

**Comment by GuyKh** [comment]
The issue is widely discussed here:
https://github.com/costastf/locationsharinglib/issues/104
